version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ulangi-server
    restart: unless-stopped
    volumes:
      - /app/node_modules
    ports:
      - '80:8082'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./config/.env
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
  npm:
    image: node:10
    working_dir: /app
    entrypoint: [ "npm" ]
    volumes:
      - ./:/app
#Volumes
volumes:
  dbdata:
    driver: local